USE Pizzeria;

INSERT INTO pizzasize (PizzaSizeName) VALUES
('Small'),
('Medium'),
('Large'),
('XLarge');

INSERT INTO pizzacrust (PizzaCrustName) VALUES
('Thin'),
('Original'),
('Pan'),
('Gluten-Free');

INSERT INTO topping (ToppingName, ToppingCustomerPrice, ToppingCompanyCost, ToppingCurInventory) VALUES
('Pepperoni', 1.25, 0.2, 100),
('Sausage', 1.25, 0.15, 100),
('Ham', 1.5, 0.15, 78),
('Chicken', 1.75, 0.25, 56),
('Green Pepper', 0.5, 0.02, 79),
('Onion', 0.5, 0.02, 85),
('Roma Tomato', 0.75, 0.03, 86),
('Mushrooms', 0.75, 0.1, 52),
('Black Olives', 0.6, 0.1, 39),
('Pineapple', 1, 0.25, 15),
('Jalapenos', 0.5, 0.05, 64),
('Banana Peppers', 0.5, 0.05, 36),
('Regular Cheese', 1.5, 0.12, 250),
('Four Cheese Blend', 2, 0.15, 150),
('Feta Cheese', 2, 0.18, 75),
('Goat Cheese', 2, 0.2, 54),
('Bacon', 1.5, 0.25, 89);

INSERT INTO toppingamount (ToppingAmountToppingID, ToppingAmountPizzaSizeID, ToppingAmountUnitQty) VALUES 
((SELECT ToppingID FROM topping WHERE ToppingName='Pepperoni'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Pepperoni'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 2.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Pepperoni'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 3.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Pepperoni'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 4.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Sausage'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Sausage'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 3),
((SELECT ToppingID FROM topping WHERE ToppingName='Sausage'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 3.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Sausage'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 4.25),
((SELECT ToppingID FROM topping WHERE ToppingName='Ham'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Ham'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 2.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Ham'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 3.25),
((SELECT ToppingID FROM topping WHERE ToppingName='Ham'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 4),
((SELECT ToppingID FROM topping WHERE ToppingName='Chicken'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Chicken'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Chicken'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 2.25),
((SELECT ToppingID FROM topping WHERE ToppingName='Chicken'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 3),
((SELECT ToppingID FROM topping WHERE ToppingName='Green Pepper'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Green Pepper'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Green Pepper'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Green Pepper'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 2.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Onion'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Onion'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Onion'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Onion'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 2.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Roma Tomato'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Roma Tomato'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 3),
((SELECT ToppingID FROM topping WHERE ToppingName='Roma Tomato'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 3.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Roma Tomato'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 4.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Mushrooms'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Mushrooms'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Mushrooms'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 2.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Mushrooms'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 3),
((SELECT ToppingID FROM topping WHERE ToppingName='Black Olives'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 0.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Black Olives'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Black Olives'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Black Olives'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Pineapple'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Pineapple'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1.25),
((SELECT ToppingID FROM topping WHERE ToppingName='Pineapple'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 1.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Pineapple'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Jalapenos'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 0.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Jalapenos'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 0.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Jalapenos'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 1.25),
((SELECT ToppingID FROM topping WHERE ToppingName='Jalapenos'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 1.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Banana Peppers'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 0.6),
((SELECT ToppingID FROM topping WHERE ToppingName='Banana Peppers'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Banana Peppers'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 1.3),
((SELECT ToppingID FROM topping WHERE ToppingName='Banana Peppers'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 1.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Regular Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Regular Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 3.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Regular Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 5),
((SELECT ToppingID FROM topping WHERE ToppingName='Regular Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 7),
((SELECT ToppingID FROM topping WHERE ToppingName='Four Cheese Blend'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Four Cheese Blend'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 3.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Four Cheese Blend'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 5),
((SELECT ToppingID FROM topping WHERE ToppingName='Four Cheese Blend'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 7),
((SELECT ToppingID FROM topping WHERE ToppingName='Feta Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Feta Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 3),
((SELECT ToppingID FROM topping WHERE ToppingName='Feta Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 4),
((SELECT ToppingID FROM topping WHERE ToppingName='Feta Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 5.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Goat Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1.6),
((SELECT ToppingID FROM topping WHERE ToppingName='Goat Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 2.75),
((SELECT ToppingID FROM topping WHERE ToppingName='Goat Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 4),
((SELECT ToppingID FROM topping WHERE ToppingName='Goat Cheese'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 5.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Bacon'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 1),
((SELECT ToppingID FROM topping WHERE ToppingName='Bacon'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 1.5),
((SELECT ToppingID FROM topping WHERE ToppingName='Bacon'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 2),
((SELECT ToppingID FROM topping WHERE ToppingName='Bacon'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 3);


INSERT INTO discount (DiscountName, DiscountPercentageAmount, DiscountDollarAmount) VALUES
('Employee', 15, NULL),
('Lunch Special Medium', NULL, 1.00),
('Lunch Special Large', NULL, 2.00),
('Specialty Pizza', NULL, 1.50),
('Gameday Special', 20, null),
('Happy Hour', 10, NULL);


INSERT INTO pizzabase (PizzaBaseCrustPizzaCrustID, PizzaBasePizzaSizeID, PizzaBaseCustomerPrice, PizzaBaseCompanyCost) VALUES 
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Thin'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 3, 0.5),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Original'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 3, 0.75),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Pan'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 3.5, 1),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Gluten-Free'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Small'), 4, 2),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Thin'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 5, 1),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Original'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 5, 1.5),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Pan'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 6, 2.25),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Gluten-Free'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Medium'), 6.25, 3),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Thin'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 8, 1.25),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Original'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 8, 2),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Pan'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 9, 3),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Gluten-Free'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='Large'), 9.5, 4),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Thin'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 10, 2),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Original'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 10, 3),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Pan'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 11.5, 4.5),
((SELECT PizzaCrustID FROM pizzacrust WHERE PizzaCrustName='Gluten-Free'), 
(SELECT PizzaSizeID FROM pizzasize WHERE PizzaSizeName='XLarge'), 12.5, 6);

INSERT INTO address (AddressHouseNum, AddressStreet, AddressCity, AddressState, AddressZipcode) VALUES
('115', 'party blvd', 'Anderson', 'SC', '29621'),
('6745', 'wessex st', 'Anderson', 'SC', '29621'),
('8879', 'suburban home', 'Anderson', 'SC', '29621');

INSERT INTO customer (CustomerFirstName, CustomerLastName, CustomerPhone, CustomerAddressAddressID) VALUES
('INSTORE', 'customer', '0000000000', NULL),
('Andrew', 'Wilkes-Krier', '8642545861', 1),
('Matt', 'Engers', '8644749953', NULL),
('Frank', 'Turner', '8642328944', 2),
('Milo', 'Auckerman', '8648785679', 3);

INSERT INTO customerorder (CustomerOrderOrderType, CustomerOrderCustomerID, CustomerOrderCustomerPrice, CustomerOrderCompanyCost, CustomerOrderTimestamp, CustomerOrderComplete) VALUES 
('dinein', NULL, 13.5, 3.68, '2021-03-05 12:03:00', true),
('dinein', NULL, 17.35, 4.63, '2022-04-03 12:05:00', true),
('pickup', 1, 64.5, 19.8, '2022-03-03 21:30:00', true),
('delivery', 1, 45.00, 16.86, '2022-04-20 19:11:00', true),
('pickup', 2, 16.85, 7.85, '2022-03-02 17:30:00', true),
('delivery', 3, 13.25, 3.2, '2022-03-02 18:17:00', true),
('delivery', 4, 24.00, 6.30, '2022-04-13 20:32:00', true);

INSERT INTO pizza (PizzaPizzaBaseID, PizzaCustomerPrice, PizzaCompanyCost) VALUES 
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 1), 13.50, 3.68),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 2 AND PizzaBaseCrustPizzaCrustID = 3), 10.60, 3.23),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 1 AND PizzaBaseCrustPizzaCrustID = 2), 6.75, 1.40),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 2), 10.75, 3.30),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 4 AND PizzaBaseCrustPizzaCrustID = 2), 14.50, 5.59),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 4 AND PizzaBaseCrustPizzaCrustID = 2), 17.00, 5.59),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 4 AND PizzaBaseCrustPizzaCrustID = 2), 14.00, 5.68),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 4 AND PizzaBaseCrustPizzaCrustID = 4), 16.85, 7.85),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 1), 13.25, 3.20),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 1), 12.00, 3.75),
((SELECT PizzaBaseID FROM pizzabase WHERE PizzaBasePizzaSizeID = 3 AND PizzaBaseCrustPizzaCrustID = 1), 12.00, 2.55);

INSERT INTO pizzatopping (PizzaToppingPizzaID, PizzaToppingToppingID, PizzaToppingExtraTopping) VALUES 
(1, 13, TRUE),
(1, 1, FALSE),
(1, 2, FALSE),
(2, 15, FALSE),
(2, 9, FALSE),
(2, 7, FALSE),
(2, 8, FALSE),
(2, 12, FALSE),
(3, 13, FALSE),
(3, 4, FALSE),
(3, 12, FALSE),
(4, 13, FALSE),
(4, 1, FALSE),
(5, 13, FALSE),
(5, 1, FALSE),
(6, 13, FALSE),
(6, 1, FALSE),
(7, 13, FALSE),
(7, 1, FALSE),
(8, 13, FALSE),
(8, 1, FALSE),
(9, 13, FALSE),
(9, 1, FALSE),
(10, 1, FALSE),
(10, 2, FALSE),
(10, 14, FALSE),
(11, 3, TRUE),
(11, 10, TRUE),
(12, 11, FALSE),
(12, 17, FALSE),
(12, 14, FALSE),
(13, 5, FALSE),
(13, 6, FALSE),
(13, 7, FALSE),
(13, 8, FALSE),
(13, 9, FALSE),
(13, 16, FALSE),
(14, 4, FALSE),
(14, 5, FALSE),
(14, 6, FALSE),
(14, 8, FALSE),
(14, 14, TRUE),
(15, 14, TRUE),
(16, 13, FALSE),
(16, 1, TRUE);

INSERT INTO pizzacustomerorder (PizzaCustomerOrderPizzaID, PizzaCustomerOrderCustomerOrderID, PizzaCustomerOrderStatus) VALUES 
(1, 1, 'done'),
(2, 2, 'done'),
(3, 2, 'done'),
(4, 3, 'done'),
(5, 3, 'done'),
(6, 3, 'done'),
(7, 3, 'done'),
(8, 3, 'done'),
(9, 3, 'done'),
(10, 4, 'done'),
(11, 4, 'done'),
(12, 4, 'done'),
(13, 5, 'done'),
(14, 5, 'done'),
(15, 6, 'done');

INSERT INTO dinein (DineInOrderID, DineInTableID) VALUES 
(1, 1),
(2, 4);

INSERT INTO delivery (DeliveryOrderID, DeliveryAddress) VALUES 
(4, '115 Party Blvd Anderson, SC 29621'),
(6, '6745 Wessex st Anderson, SC 29621'),
(7, '8879 Suburban home Anderson, SC 2961');

INSERT INTO pickup (PickupOrderID, PickupIsPickedUp) VALUES
(3, true),
(5, true);

INSERT INTO pizzadiscount (PizzaDiscountPizzaID, PizzaDiscountDiscountID) VALUES
(1, 3),
(2, 2),
(3, 4),
(11, 4);

INSERT INTO orderdiscount (OrderDiscountDiscountID, OrderDiscountOrderID) VALUES
(4, 5);